### ISSUE TITLE
How dose this lib impact app performance?

### ISSUE THREAD

**Issue by amy1602** [facebookincubator/profilo#19]
I see lib has loop to trace until stop tracing. So, how dose this lib impact app performance? (or overhead of lib)

**Comment by aandreyeu** [comment]
The library is designed to keep the overhead at minimum, however, it's not completely free. 
The overhead depends on many factors as the type of the measured interaction, application logic, hardware resources, OS version, etc. so I can't you provide you with any numbers for overhead. It best can be measured within the instrumented app.
The most important one is the enabled providers mix. The key of thumb here is to use only necessary providers, rather than just enable all of them, to keep the overhead low.

**Comment by amy1602** [comment]
Hi, How can I get exact boundaries of a frame and app responsiveness from trace log?
