### ISSUE TITLE
Attach source code to existing project

### ISSUE THREAD

**Issue by AndrejLee** [facebookincubator/profilo#24]
Excuse me, for my curiosity, is there any way to use directly provided Profilo's source code to my project without using .aar file? Please give me some information if you can. Thanks.

**Comment by ricardorey10** [comment]
Unfortunately, right now it's not possible. You can make changes to the code and [build using the Docker container](https://facebookincubator.github.io/profilo/docs/getting-started.html#use-a-prebuilt-aar-with-gradle) (see the section titled **Building from source**), but that will also just generate a new `.aar`.

This situation is caused because we use Buck to build, which is necessary due to a large dependency graph and a non-trivial amount of native code. As you can see in the TODO section from the above link, we have plans to migrate the build to Gradle + Maven Central artifacts, so we'll get there eventually, but it's probably not going to happen particularly soon.
