### ISSUE TITLE
AGPBI: {"kind":"error","text":"Program type already present: javax.annotation.CheckForNull","sources":[{}],"tool":"D8"}

### ISSUE THREAD

**Issue by lizuojing** [facebookincubator/profilo#39]
It happens when i import profilo.aar into my project.How to resolve it.

**Comment by aandreyeu** [comment]
This conflict happens because `javax.annotation.CheckForNull` class (and others from `jsr-305` annotations) are already in your classpath from a different library. The easiest way to resolve the issue is to remove the jar containing the conflicting annotations from your classpath, so those classes will be used from `profilo.aar`. I can't suggest any concrete steps as it depends on specifics of you project and development environment.

We currently don't have an option to build the aar without the specific dependencies.
