### ISSUE TITLE
Systrace Snooping Supports Less Than Half the Market?

### ISSUE THREAD

**Issue by AttwellBrian** [facebookincubator/profilo#4]
Systrace snooping doesn't work [on/above Marshmallow](https://github.com/facebookincubator/profilo/blob/802042f90f990998a272387e371b893af52465b8/cpp/atrace/Atrace.cpp#L202). Is it impossible to setup the hooks on these OS versions? Or just not done yet?

_Aside: thanks for open sourcing this :)_

**Comment by BurntBrunch** [comment]
Coming imminently, we have it working internally but we need to clean it up
for release.

On Mar 13, 2018 12:24 PM, "Brian Attwell" <notifications@github.com> wrote:

Systrace snooping doesn't work on/above Marshmallow
<https://github.com/facebookincubator/profilo/blob/802042f90f990998a272387e371b893af52465b8/cpp/atrace/Atrace.cpp#L202>.
Is it impossible to setup the hooks on these OS versions? Or just not done
yet?

*Aside: thanks for open sourcing this :)*

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/facebookincubator/profilo/issues/4>, or mute the thread

**Comment by AttwellBrian** [comment]
Awesome!

If you don't mind I'll leave this Issue open to track the update. Or, if you folks don't like using github Issues internally I don't mind if you close this Issue :)

**Comment by ricardorey10** [comment]
ce50933 fixes this.
